# Generated by Django 6.0 on 2025-12-24 00:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField()),
                ('requested_grade', models.CharField(blank=True, max_length=40)),
                ('guardian_name', models.CharField(max_length=120)),
                ('guardian_phone', models.CharField(blank=True, max_length=40)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_relationship', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('admitted_student_id', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
